### ISSUE TITLE
ERRORs that happended in the process of enabling Power Manager

### ISSUE THREAD

**Issue by shaorui0** [intel/kubernetes-power-manager#13]
Some errors occurred during enable power manager.
log command: 
`kubectl logs  -n intel-power power-node-agent-s4h4p -c power-node-agent`

Here are some log messages:

### 1. cannot check status of pod 

error message: 
```
{"reconcilerGroup": "", "reconcilerKind": "Pod", "controller": "pod", "name": "power-node-agent-s4h4p", "namespace": "intel-power", "error": "pod not in running phase"}
```

But the status of my pod is started normally.
```sh
$kubectl get pods -n intel-power

NAME                                 READY   STATUS    RESTARTS   AGE
controller-manager-74b6b8589-wr2q8   1/1     Running   0          23h
power-node-agent-s4h4p               2/2     Running   0          2d
```

### 2. network error

error message: 
```
{"reconcilerGroup": "power.intel.com", "reconcilerKind": "PowerWorkload", "controller": "powerworkload", "name": "balance-performance-master-workload", "namespace": "default", "error": "Get https://localhost:5000/power_profiles: dial tcp 127.0.0.1:5000: connect: connection refused"}
{"reconcilerGroup": "power.intel.com", "reconcilerKind": "PowerNode", "controller": "powernode", "name": "master", "namespace": "default", "error": "Get https://localhost:5000/pools: dial tcp 127.0.0.1:5000: connect: connection refused"}
```
This error may related to previous one.

```
{"powerprofile": "default/balance-performance", "error": "Response status code error"}
{"powerprofile": "default/balance-power", "error": "Response status code error"}
{"powerprofile": "default/performance", "error": "Response status code error"}
{"powerprofile": "default/shared", "error": "Response status code error"}
```

### 3. json unmarshal error

error message: 
```
{"reconcilerGroup": "power.intel.com", "reconcilerKind": "PowerWorkload", "controller": "powerworkload", "name": "shared-master-workload", "namespace": "default", "error": "json: cannot unmarshal object into Go value of type []appqos.PowerProfile"}
```
This error may be a code error.

**Comment by pbrownlow7** [comment]
Hi @shaorui0, thanks for reaching out.

For the first issue, this is the expected behaviour of the power manager, when it tries to reconcile a Pod it checks to make sure it is running. If it is not (the most common example is if the container is in the ContainerCreation phase) it will requeue the reconciliation and try again until the Pod is in the Running phase.

The second and third issues are linked, I think the problem is that Power Profiles/SST-CP is not enabled in your App QoS instance. Because of this the power_profiles target doesn't exist so no power profile can be created, and then when the workload is trying to unmarshal the response from the App QoS agent it expects at least one value but it is getting nothing, hence the error.

Can you show me the logs for the App QoS agent by running this command:
kubectl logs -n intel-power power-node-agent-s4h4p -c appqos

**Comment by shaorui0** [comment]
Hi @pbrownlow7 , here are some log messages. And I find that all connections to /pools are `200`, but all connections to /profile are `404`


kubectl logs -n intel-power power-node-agent-s4h4p -c appqos
```
127.0.0.1 - - [2022-01-26 19:58:53] "GET /pools HTTP/1.1" 200 333 0.000489
127.0.0.1 - - [2022-01-26 19:58:58] "POST /power_profiles HTTP/1.1" 404 259 0.000631
127.0.0.1 - - [2022-01-26 19:58:58] "GET /pools HTTP/1.1" 200 333 0.001557
127.0.0.1 - - [2022-01-26 19:58:58] "GET /pools HTTP/1.1" 200 333 0.000511
127.0.0.1 - - [2022-01-26 19:59:03] "GET /pools HTTP/1.1" 200 333 0.000534
```


$ kubectl logs -n intel-power power-node-agent-s4h4p -c appqos | grep 404
```
127.0.0.1 - - [2022-01-26 19:44:52] "POST /power_profiles HTTP/1.1" 404 259 0.000551
127.0.0.1 - - [2022-01-26 19:51:41] "GET /power_profiles HTTP/1.1" 404 259 0.000554
127.0.0.1 - - [2022-01-26 19:51:43] "GET /power_profiles HTTP/1.1" 404 259 0.000550
127.0.0.1 - - [2022-01-26 19:51:44] "GET /power_profiles HTTP/1.1" 404 259 0.000553
127.0.0.1 - - [2022-01-26 19:51:58] "POST /power_profiles HTTP/1.1" 404 259 0.000558
127.0.0.1 - - [2022-01-26 19:51:59] "POST /power_profiles HTTP/1.1" 404 259 0.000566
127.0.0.1 - - [2022-01-26 19:58:58] "POST /power_profiles HTTP/1.1" 404 259 0.000631
127.0.0.1 - - [2022-01-26 20:00:33] "POST /power_profiles HTTP/1.1" 404 259 0.000586
127.0.0.1 - - [2022-01-26 20:01:32] "POST /power_profiles HTTP/1.1" 404 259 0.000575

```

**Comment by pbrownlow7** [comment]
Hi @shaorui0, so the fact that you are getting a 200 response from the appqos agent when requesting pools and a 404 response when requesting power_profiles definitely indicates that SST-CP isn't enabled on the machine. For appqos to be able to utilize power profiles, this feature needs to be enabled on your machine.

Just to be certain, when you first deploy the power node agent, in the logs for the appqos agent's container, does it say PowerProfiles/SST-CP is enabled or disabled?

So for example, this is what it would say if that feature was enabled:
2022-01-26 15:31:19,501 INFO  Interface MSR, MBA BW: unsupported.
2022-01-26 15:31:19,600 INFO  Interface OS, MBA BW: supported.
2022-01-26 15:31:19,601 INFO  Supported RDT interfaces: ['msr', 'os']
2022-01-26 15:31:19,650 INFO  RDT initialized with 'msr' interface
2022-01-26 15:31:20,668 INFO  Supported capabilities:
2022-01-26 15:31:20,668 INFO  ['l3cat', 'mba']
2022-01-26 15:31:20,755 INFO  SST-BF not enabled
**2022-01-26 15:31:20,755 INFO  Power Profiles/SST-CP enabled.**
2022-01-26 15:31:20,755 INFO  Configuring RDT
2022-01-26 15:31:20,761 INFO  RDT MBA CTRL disabled

**Comment by shaorui0** [comment]
hi @pbrownlow7 , I have created a new power-node-agent and it say "Power Profiles/EPP not enabled". Why did this happen?

[root@master kubernetes-power-manager]# kubectl logs -n intel-power power-node-agent-rbcj8 -c appqos
2022-01-27 04:36:24,475 ERROR libpqos is_mba_ctrl_enabled(..) call failed!
2022-01-27 04:36:24,475 ERROR ('pqos_mba_ctrl_enabled returned 3', 3)
2022-01-27 04:36:24,475 INFO  Interface MSR, MBA BW: unsupported.
ERROR: os_cap_init() error 3
2022-01-27 04:36:24,484 ERROR ('pqos_init returned 3', 3)
2022-01-27 04:36:24,484 INFO  Supported RDT interfaces: ['msr']
2022-01-27 04:36:24,491 ERROR libpqos is_mba_ctrl_enabled(..) call failed!
2022-01-27 04:36:24,491 ERROR ('pqos_mba_ctrl_enabled returned 3', 3)
2022-01-27 04:36:24,491 INFO  RDT initialized with 'msr' interface
2022-01-27 04:36:24,491 ERROR ('pqos_mba_get_cos_num returned 3', 3)
2022-01-27 04:36:24,502 INFO  Supported capabilities:
2022-01-27 04:36:24,502 INFO  ['l3cat']
2022-01-27 04:36:24,561 INFO  SST-BF not enabled
**2022-01-27 04:36:24,561 INFO  Power Profiles/EPP not enabled**
2022-01-27 04:36:24,561 INFO  Configuring RDT
2022-01-27 04:36:24,566 INFO  Configuration changed, processing new config...
2022-01-27 04:36:24,571 INFO  New configuration processed

**Comment by pbrownlow7** [comment]
Hi @shaorui0, apologies for the delay.

The issue is with how App QoS initializes. App QoS doesn't seem to be detecting that SST-CP is enabled on the Node. Unfortunately, with how App QoS works, if SST-CP is not detected, Power Profiles/EPP won't be enabled which means that power profiles can't be used. Without power profiles in App QoS the power manager can't work as the power profiles are what hold all the relevant information for core configuration.

If your system has the capability to run SST-CP and it is configured, App QoS should be able to detect it properly.

Another option, which is a hack to get around it, is to force App QoS to return that SST-CP is enabled by simply changing the code to return True when querying the system in the App QoS source code and rebuilding the image, forcing power profiles to be available.

We'll be moving away from App QoS in a future release so this will only be a temporary solution to this problem and deploying the power manager will hopefully be a lot easier.

**Comment by patricia-cahill** [comment]
pbrowlow7  replied to this issues, and as App QoS in not in V2 its N/A now
