### ISSUE TITLE
common cstates configuration for all the power nodes instead of creating separate for each node

### ISSUE THREAD

**Issue by sahanirn** [intel/kubernetes-power-manager#59]
Would like to understand the reason behind the current approach of applying cstates configuration for each node separately rather than having a option to apply for all the power nodes using powernodeSelector just like we have one while creating power config(power profiles). @pbrownlow7 
Current approach: 
<img width="555" alt="image" src="https://github.com/intel/kubernetes-power-manager/assets/99477098/684a531b-5b33-4456-bd7b-bdc59f75ed8c">

**Comment by adorney99** [comment]
Hi @sahanirn, sorry for the late response.  The reason we require the node name is because objects like this work on a node per node basis and need to be correctly identified because CRD reconcile requests can get sent to the wrong node. Power profiles don't need a node name because they are cluster wide but powerworkloads using that profile do because they operate on a node. Implementing something like you described might be feasible using the powerconfig to generate these per-node objects on the fly and deploy them to each node matching a selector. This would involve keeping track of multiple groupings of nodes as they would need to be grouped based on hardware constraints. This might be useful for people who want to configure multiple nodes with the same hardware. Adding something like this isn't currently a high priority but we'll consider it as a future feature. Thanks so much for your feedback

**Comment by adorney99** [comment]
closing issue as backlog items exist for supporting cluster wide operations like this
